# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductClean' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductClean
	pod 'SDWebImageSwiftUI'
  target 'ProductCleanSnapshotTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'iOSSnapshotTestCase'
  end

  target 'ProductCleanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductCleanUITests' do
    # Pods for testing
  end

end
